name:                tasktags
version:             0.1

dependencies:
- aeson
- base
- bytestring
- containers
- directory
- email-validate
- filepath
- http-client
- http-types
- ini
- lens
- lens-aeson
- optparse-applicative
- pandoc
- parsec
- split
- text
- time
- unordered-containers
- wreq

library:
  source-dirs: src

executables:
  keepToMd:
    main:                keepToMd.hs
    source-dirs:         app
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasktags

  togglCsv:
    main:                togglCsv.hs
    source-dirs:         app
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasktags

  togglSubmit:
    main:                togglSubmit.hs
    source-dirs:         app
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasktags

tests:
  tasktags-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasktags
    - hspec
