name:                tasktags
version:             0.1

dependencies:
- aeson
- base
- bytestring
- containers
- directory
- email-validate
- filepath
- http-client
- http-types
- ini
- lens
- lens-aeson
- optparse-applicative
- pandoc
- parsec
- split
- text
- time
- unordered-containers
- wreq

library:
  source-dirs: src

flags:
  release:
    default: false
    manual: true

ghc-options: -Wall -Werror -Wno-missing-signatures -Wno-name-shadowing -Wno-unused-do-bind -Wno-orphans -Wno-type-defaults

_release-exe-ghc-options: &release-exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

_dev-exe-ghc-options: &dev-exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -dynamic

executables:
  keepToMd:
    main:                keepToMd.hs
    source-dirs:         app
    when:
      condition: flag(release)
      then:
        ghc-options:
          *release-exe-ghc-options
      else:
        ghc-options:
          *dev-exe-ghc-options
    dependencies:
    - tasktags

  togglCsv:
    main:                togglCsv.hs
    source-dirs:         app
    when:
      condition: flag(release)
      then:
        ghc-options:
          *release-exe-ghc-options
      else:
        ghc-options:
          *dev-exe-ghc-options
    dependencies:
    - tasktags

  togglSubmit:
    main:                togglSubmit.hs
    source-dirs:         app
    when:
      condition: flag(release)
      then:
        ghc-options:
          *release-exe-ghc-options
      else:
        ghc-options:
          *dev-exe-ghc-options
    dependencies:
    - tasktags

tests:
  tasktags-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -dynamic
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasktags
    - hspec
